# Generated by Django 3.0.10 on 2020-10-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='codigo',
            field=models.CharField(default='001', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
