# Generated by Django 3.0.10 on 2020-10-04 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_auto_20201004_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.Store'),
        ),
    ]
