# Generated by Django 3.0.10 on 2020-10-08 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_purchase_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='codigo',
            new_name='code',
        ),
    ]
